#!/usr/bin/bash

# fail script on any error
set -e

PROG_NAME=$1
NUMBER=$2

echo "Running ${PROG_NAME} test #${NUMBER}:"

PROGRAM="${PROG_NAME}.py"
TESTFILE="${PROG_NAME}.tc${NUMBER}"
ANSWERFILE="${PROG_NAME}.an${NUMBER}"
OUTFILE="${PROG_NAME}.out${NUMBER}"
TEMPOUT="${PROG_NAME}.out.temp${NUMBER}"
TEMPANS="${PROG_NAME}.an.temp${NUMBER}"
TEMPDIF="${PROG_NAME}.diff.temp${NUMBER}"
FAIL=0
FILES=""
if [ ! -f $PROGRAM ]; then
	echo "Python file ${PROGRAM} doesn't exist"
	FAIL=1
	FILES="${FILES}${PROGRAM} "
fi
if [ ! -f $TESTFILE ]; then
	echo "Test file ${TESTFILE} doesn't exist"
	FAIL=1
	FILES="${FILES}${TESTFILE} "
fi
if [ ! -f $ANSWERFILE ]; then
	echo "Answer file ${ANSWERFILE} doesn't exist"
	FAIL=1
	FILES="${FILES}${ANSWERFILE} "
fi
if [ -f $OUTFILE ]; then
	echo "Output file ${OUTFILE} already exists, overwriting"
fi
if [ "1" = $FAIL ]; then
	echo "Quitting.  Fix missing files with:"
	echo "vi ${FILES}"
	exit 1
fi

ulimit -m 1024000	# physical memory hard limit 1G
ulimit -v 1024000	# virtual memory hard limit 1G

#time (			\
#	python $PROGRAM < $TESTFILE		\
#	|| (		\
#	    echo "Failed with exit code $?"	\
#	    && exit	\
#	)		\
#     ) | tee $OUTFILE
#
time  python $PROGRAM < $TESTFILE	\
	| tee $OUTFILE

echo ""
echo "Differences:"
echo ""
echo "ACTUAL" > $ACTUAL

cat $OUTFILE						\
	| grep -v '^\s*[#]'				\
	| grep -n '.'					\
	> $TEMPOUT
(echo "EXPECTED"					\
    && cat $ANSWERFILE					\
	| grep -n '.'					\
) > $TEMPANS
diff -sq $TEMPOUT $TEMPANS				\
	| sed -e 's,[.]temp,,g'
diff -q $TEMPOUT $TEMPANS > /dev/null			\
    || (						\
    diff -s -W $(tput cols) -y $TEMPOUT $TEMPANS	\
        | grep '\s[<|>]\s'				\
	| tee $TEMPDIF					\
	| head -n 20					\
    && cat $TEMPDIF					\
	| tail -n +21					\
	| grep -c .					\
	| sed -e 's,\([0-9]*\),... \1 more lines,'	\
	| grep -v ' 0 '					\
    )

rm $TEMPOUT $TEMPANS

